server:
  port: 8085

eureka:
  client:
    service-url: http://localhost:8761/eureka
spring:
  application:
    name: zuul
zuul:
  routes:
      devweb:
        path:/devweb/**
        serviceId:web







